# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daylight < Formula
  desc "track sunrise / sunset times for your date and location"
  homepage ""
  version "1.0.0"
  license "unlicensed"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jbreckmckye/daylight/releases/download/v1.0.0/daylight_Darwin_x86_64.tar.gz"
      sha256 "f3b8acb725240445293442a0329a5cce926abee3c7be4973d42b4461a7d214af"

      def install
        bin.install "daylight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbreckmckye/daylight/releases/download/v1.0.0/daylight_Darwin_arm64.tar.gz"
      sha256 "bc6ce8ec55eeb421c7b492b985651344cde180ff7f8af612df2429c77703aa2b"

      def install
        bin.install "daylight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jbreckmckye/daylight/releases/download/v1.0.0/daylight_Linux_x86_64.tar.gz"
        sha256 "14b8e450f8e79376ed235a55c6e3cadfea2d1bd9c065ede511631ceeb23709cd"

        def install
          bin.install "daylight"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jbreckmckye/daylight/releases/download/v1.0.0/daylight_Linux_arm64.tar.gz"
        sha256 "aa982fd4e50010f09477ac6948df5f7605c08e26d01a07af2c4233c6f9d05076"

        def install
          bin.install "daylight"
        end
      end
    end
  end

  def caveats
    <<~EOS
      daylight is very new, so be sure to check for updates and report any bugs
    EOS
  end

  test do
    daylight --help
  end
end
