# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daylight < Formula
  desc "track sunrise / sunset times for your date and location"
  homepage ""
  version "1.1.0"
  license "unlicensed"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jbreckmckye/daylight/releases/download/v1.1.0/daylight_Darwin_x86_64.tar.gz"
      sha256 "a77ee401f551434a22eba4814dd09a0c3508828f5b26f5befe246c6203e465e4"

      def install
        bin.install "daylight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbreckmckye/daylight/releases/download/v1.1.0/daylight_Darwin_arm64.tar.gz"
      sha256 "6deb224912704808aa0c26c7d0d4cc5b7e0b4b972e8a422df5313986051c874d"

      def install
        bin.install "daylight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jbreckmckye/daylight/releases/download/v1.1.0/daylight_Linux_x86_64.tar.gz"
        sha256 "b61c083240aa95c4e5e5e672ab036acf3340d4124bada7ea82dc5f2b4a3c9b44"

        def install
          bin.install "daylight"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jbreckmckye/daylight/releases/download/v1.1.0/daylight_Linux_arm64.tar.gz"
        sha256 "30ae66f2ae730b03a16543dd97278c74880fcae89332b1b8942dfa8f49a89f70"

        def install
          bin.install "daylight"
        end
      end
    end
  end

  def caveats
    <<~EOS
      daylight is very new, so be sure to check for updates and report any bugs
    EOS
  end

  test do
    daylight --help
  end
end
